#!/usr/bin/python3
# SpDX-FileCopyrightText: 2023 Kohsei Takaoka ta.kousei0226@gmail.com
# SPDX-License-Identifier:BSD-3-Clause

import sys

ans1 = 0
ans2 = 0
for line in sys.stdin:
    try:
        num = int(line)
        ans1 += num
        ans2 -= num
    except:
        num = float(line)
        ans1 += num
        ans2 -= num

lst1 = list(range(1, num + 1))
print(lst1, "=", ans1)

lst2 = list(range(-num, num - num))
print(lst2, "=", ans2)
