#!/usr/bin/python3
# SpDX-FileCopyrightText: 2023 Kohsei Takaoka ta.kousei0226@gmail.com
# SPDX-License-Identifier:BSD-3-Clause

import sys

ans = 0
for line in sys.stdin:
    try:
        num = int(line)
        ans += num
    except:
        num = float(line)
        ans += num

lst = list(range(1, num + 1))
print(lst)
print("=", ans)
